#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Extra paper-2 tables generated from frozen result files (called by make_paper2_v2_tables.py):

  backbone_seeds.tex   main text: per-seed R1-R4 verdicts of every other backbone (seeds 42/43/44)
  seed_labels.tex      main text: seedlabel / seeddetail macros (labels across seeds)
  rtc_supp.tex         supplement: read-then-convert hypotheses per adapter + per-cell R/f
  t36_supp.tex         supplement: zero-shot sweep (descriptive; one INVALID cell marked)
  repr_probe_supp.tex  supplement: representation-probe verdict stability over 10 fold seeds

Also returns a dict of the numbers the text quotes (written into paper2_v2_numbers.json under
"extra") so that tools/audit_paper2_v2.py / audit_paper2_supp.py can recompute them.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CD = ROOT / "results" / "courtdyn"
TABLES = ROOT / "paper2" / "manuscript_v2" / "tables"
NAMES = {"qwen25vl3b": "Qwen2.5-VL-3B", "internvl3_2b": "InternVL3-2B", "smol": "SmolVLM2-2.2B",
         "pixtral_12b": "Pixtral-12B", "idefics3_8b": "Idefics3-8B", "gemma3_12b": "Gemma3-12B"}
ORDER = ["qwen25vl3b", "internvl3_2b", "pixtral_12b", "idefics3_8b", "gemma3_12b", "smol"]
RULES = [("R1", "R1"), ("R2_E", "R2-E"), ("R2_T", "R2-T"), ("R3", "R3"), ("R4", "R4")]
ABBR = {"replicates": "rep.", "intermediate": "int.", "LIMITED": "unt.", "fails": "fails", None: "--"}


def j(p):
    return json.loads(Path(p).read_text(encoding="utf-8"))


# ------------------------------------------------------------------ seeds table
def seeds_block():
    agg = j(CD / "backbone_seeds3" / "aggregate.json")["backbones"]
    out = {}
    for key in ORDER:
        e = agg[key]
        per = {r: {s: e[r]["per_seed"].get(str(s)) for s in (42, 43, 44)} for r, _ in RULES}
        n_seeds = max(e[r]["n_seeds_judged"] for r, _ in RULES)
        out[key] = {"per_seed": per, "n_seeds": n_seeds, "labels": {r: e[r]["label"] for r, _ in RULES},
                    "descriptive": e["descriptive_only"]}
    return out


# label across seeds (aggregate_backbone_seeds.py vocabulary) -> table mark and text verb phrase
LABEL_MARK = {"holds at all three seeds": "3/3", "holds at two of three seeds": "2/3",
              "fails across seeds": "fails", "seed-dependent": "s.-d.", "not established": "n.e.",
              "pending": ""}
LABEL_TEXT = {"holds at all three seeds": "holds at all three seeds",
              "holds at two of three seeds": "holds at two of three seeds",
              "fails across seeds": "fails across seeds", "seed-dependent": "is seed-dependent",
              "not established": "is not established"}
DETAIL = {"replicates": "replicates", "intermediate": "intermediate", "LIMITED": "untestable",
          "fails": "fails"}


def seed_detail(per):
    """'seed 42: fails; 43: intermediate; 44: replicates' (seeds not yet judged are omitted)."""
    parts = [(s, DETAIL[v]) for s, v in sorted(per.items()) if v is not None]
    return "; ".join((f"seed {s}" if i == 0 else f"{s}") + f": {v}" for i, (s, v) in enumerate(parts))


def seed_labels_tex(sb):
    """\\seedlabel{key}{rule}: label across seeds as a verb phrase (\\pending while a seed is
    missing); \\seeddetail{key}{rule}: the per-seed verdicts."""
    L = ["% Generated by tools/make_paper2_extra_tables.py -- do not edit by hand.",
         r"\providecommand{\seedlabel}[2]{\csname seedlabel-#1-#2\endcsname}",
         r"\providecommand{\seeddetail}[2]{\csname seeddetail-#1-#2\endcsname}"]
    for key in ORDER:
        e = sb[key]
        for r, _ in RULES:
            lab = e["labels"][r]
            text = LABEL_TEXT.get(lab) or (r"\pending{" + f"{NAMES[key]} {r.replace('_', '-')} label" + "}")
            L.append(r"\expandafter\def\csname seedlabel-" + f"{key}-{r}" + r"\endcsname{" + text + "}")
            L.append(r"\expandafter\def\csname seeddetail-" + f"{key}-{r}" + r"\endcsname{"
                     + seed_detail(e["per_seed"][r]) + "}")
    L.append(r"\providecommand{\seedtally}{" + seed_tally(sb) + "}")
    return "\n".join(L) + "\n"


WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
         "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
         "nineteen", "twenty"]
num = lambda n: WORDS[n] if n <= 20 else str(n)


def seed_tally(sb):
    """One sentence counting the labels over all rule x backbone combinations (multiplicity summary)."""
    labs = [sb[key]["labels"][r] for key in ORDER for r, _ in RULES]
    n = len(labs)
    c = {k: labs.count(k) for k in ("holds at all three seeds", "holds at two of three seeds",
                                     "fails across seeds", "seed-dependent", "not established")}
    assert sum(c.values()) == n, (c, n)
    return (f"Of the {n} rule--backbone combinations ({num(len(RULES))} rules on {num(len(ORDER))} backbones), "
            f"{num(c['holds at all three seeds'])} hold at all three seeds, {num(c['holds at two of three seeds'])} at two of three, "
            f"{num(c['fails across seeds'])} fail across seeds, {num(c['seed-dependent'])} are seed-dependent and "
            f"{c['not established']} are not established.")


def seeds_tex(sb):
    lines = ["% Generated by tools/make_paper2_extra_tables.py -- do not edit by hand.",
             r"\begin{table}[t]", r"\centering\footnotesize", r"\setlength{\tabcolsep}{2.5pt}",
             r"\caption{The other backbones under the preregistered rules at seeds 42, 43 and 44 "
             r"(three cells per rule: seed 42 / 43 / 44). rep.\ = replicates, int.\ = intermediate, "
             r"unt.\ = untestable (fewer than three non-degenerate cells); -- = seed not run at submission. "
             r"In parentheses, the label across seeds, fixed before seeds 43 and 44 were run: "
             r"3/3 = holds at all three seeds; 2/3 = holds at two and fails at none; "
             r"fails = fails at two or more and holds at none; s.-d.\ = seed-dependent (holds at "
             r"one or more and fails at one or more); n.e.\ = not established. "
             r"Seeds 43 and 44 use the schedule selected at seed 42 (dev rule not re-run). "
             r"$^\dagger$SmolVLM2-2.2B is degenerate at the four-epoch cap: descriptive only.}",
             r"\label{tab:backbone_seeds}", r"\resizebox{\linewidth}{!}{%", r"\begin{tabular}{lcccccc}", r"\toprule",
             r"Backbone & seeds & R1 & R2-E & R2-T & R3 & R4 \\", r"\midrule"]
    for key in ORDER:
        e = sb[key]
        cells = []
        for r, _ in RULES:
            mark = LABEL_MARK[e["labels"][r]]
            cells.append(" / ".join(ABBR[e["per_seed"][r][s]] for s in (42, 43, 44))
                         + (f" ({mark})" if mark else ""))
        name = NAMES[key] + (r"$^\dagger$" if e["descriptive"] else "")
        lines.append(f"{name} & {e['n_seeds']} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ RTC
def rtc_groups():
    s42 = j(CD / "rtc" / "verdict.json")
    rep = j(CD / "rtc_rep" / "verdict.json")["groups"]
    ext = j(CD / "backbone4_ext" / "rtc" / "verdict.json")["backbones"]
    groups = [("Qwen3.5-4B, seed 42", "rtc_s42", s42, "v3s42", "m1s42"),
              ("Qwen3.5-4B, seed 43", "rtc_s43", rep["seed43"], "v3s43", "m1s43"),
              ("Qwen3.5-4B, seed 44", "rtc_s44", rep["seed44"], "v3s44", "m1s44"),
              ("InternVL3-2B", "rtc_ivl", rep["internvl3_2b"], "ivlv3", "ivlmix"),
              ("Pixtral-12B", "rtc_pixtral_12b", ext["pixtral_12b"], "pixtral_12b_v3", "pixtral_12b_mix"),
              ("Gemma3-12B", "rtc_gemma3_12b", ext["gemma3_12b"], "gemma3_12b_v3", "gemma3_12b_mix")]
    out = []
    for name, adapter, v, v3, mix in groups:
        h = v["hypotheses"]
        def cnt(key):
            x = h.get(key)
            return None if x is None else (x[0], x[1] if isinstance(x[1], int) else None)
        out.append({"name": name, "adapter": adapter, "v3": v3, "mix": mix,
                    "H1": cnt("H1_unseen_units_rtc"), "H3": cnt("H3_speed_cm_rtc"),
                    "H4": h["H4_metre_noninferiority"][0],
                    "H5": cnt("H5_motion_dependence"),
                    "H6_v3": cnt(f"H6_format_control_{v3}"), "H6_mix": cnt(f"H6_format_control_{mix}"),
                    "cells": {k: c for k, c in v["cells"].items() if k.startswith(adapter + "|rtc|")},
                    "v3_rtc_cells": {k: c for k, c in v["cells"].items() if k.startswith(v3 + "|rtc|")}})
    return out


def rtc_tex(groups):
    f = lambda x: "--" if x is None else f"{x:.2f}"
    L = ["% Generated by tools/make_paper2_extra_tables.py -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         r"\caption{Read-then-convert (RTC): preregistered hypotheses per adapter. H1: the RTC-trained "
         r"adapter converts to units unseen in training (cells of 8; holds $\ge6$); H3: centimetre speed "
         r"converts (of 2); H4: metre $\rho$ not inferior to the metre-only adapter; H5: first-frame "
         r"repetition lowers $\rho$ (of 4); H6: the metre-only (v3) and mixed-unit (M1) adapters given the "
         r"RTC output format without training convert unseen units (of 8).}",
         r"\label{tab:rtc}", r"\begin{tabular}{lcccccc}", r"\toprule",
         r"Adapter & H1 & H3 & H4 & H5 & H6 v3 & H6 M1 \\", r"\midrule"]
    def c(x):
        return "--" if x is None else (f"{x[0]} ({x[1]})" if x[1] is not None else x[0])
    for g in groups:
        L.append(f"{g['name']} & {c(g['H1'])} & {c(g['H3'])} & {g['H4']} & {c(g['H5'])} & {c(g['H6_v3'])} & {c(g['H6_mix'])} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", "",
          r"\begin{table}[t]", r"\centering\footnotesize", r"\setlength{\tabcolsep}{3pt}",
          r"\caption{RTC-trained adapters: median answer ratio over the exact factor ($R/f$; 1.00 = exact "
          r"conversion) per unseen-unit cell, with the metre-arm rank correlation $\rho$ of the same cell "
          r"in parentheses. U1 = km/h (speed) or ft (path); U2 = ft/s or mm; px = pixels with the ruler "
          r"sentence. A cell converts under the rule only if $R/f\in[1/1.5,1.5]$, the arm is non-degenerate "
          r"and $\rho\ge0.30$.}",
          r"\label{tab:rtccells}", r"\resizebox{\linewidth}{!}{%", r"\begin{tabular}{llcccccc}", r"\toprule",
          r"Adapter & clip & speed U1 & path U1 & speed U2 & path U2 & speed px & path px \\", r"\midrule"]
    for g in groups:
        for seq, short in (("Q1_top_0-30", "Q1"), ("Q2_top_480-510", "Q2")):
            cells = []
            for unit in ("U1", "U2", "pxK"):
                for fam in ("speed", "path"):
                    k = f"{g['adapter']}|rtc|{seq}|{unit}|{fam}"
                    cc = g["cells"].get(k)
                    if cc is None:
                        cells.append("--")
                    else:
                        rf = cc.get("R_over_f")
                        rho = cc.get("rho")
                        cells.append(f"{f(rf)} ({f(rho)})" + ("*" if cc.get("converts") else ""))
            L.append(f"{g['name']} & {short} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
    return ("\n".join(L) + "\n").replace("LIMITED", "untestable")   # preregistration label -> plain word


# ------------------------------------------------------------------ T36
def t36_block():
    s = j(CD / "t36" / "summary.json")
    return s["models"]


def t36_tex(models):
    f = lambda x, d=2: "--" if x is None else f"{x:.{d}f}"
    L = ["% Generated by tools/make_paper2_extra_tables.py -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering\footnotesize", r"\setlength{\tabcolsep}{3pt}",
         r"\caption{Zero-shot sweep of public backbones on the explicit unit cells (descriptive; no decision "
         r"rule was recorded). distinct = distinct parsed metre answers; $\rho$ = metre rank correlation; "
         r"$R_{\mathrm{cm}}$ and $R_{\mathrm{px}}$ = median paired cm/m and px/m answer ratios (exact: 100 "
         r"and the clip's $K$, about 27); live = both the metre and centimetre arms have $\ge3$ distinct "
         r"answers. INVALID: the bf16 Qwen3.5-4B cell was run through a loader that left the model's "
         r"thinking mode on, so no answer was produced within the token budget; it is a harness failure, "
         r"not a model result.}",
         r"\label{tab:t36}", r"\begin{tabular}{llcccccc}", r"\toprule",
         r"Model & clip & family & distinct & $\rho$ & $R_{\mathrm{cm}}$ & $R_{\mathrm{px}}$ ($K$) & live \\", r"\midrule"]
    for m, e in models.items():
        for c in e["cells"]:
            if c.get("missing"):
                continue
            a = c["arms"]["m_height"]
            live = "invalid" if e.get("invalid") else ("yes" if c["live_unit"] else "no")
            L.append(f"{m} & {c['seq'].split('_')[0]} & {c['family']} & {a['distinct']} & {f(a['rho'])} & "
                     f"{f(c['R_cm'], 1)} & {f(c['R_px'], 1)} ({f(c['R_px_reference'], 0)}) & {live} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(L) + "\n"


# ------------------------------------------------------------------ representation probe
def probe_block():
    st = j(CD / "repr_probe" / "stability.json")
    v = j(CD / "repr_probe" / "verdict.json")
    out = {}
    for model in ("base", "native", "v3", "mixunit"):
        t = st["table"][model]
        out[model] = {"H1_speed_true": t["speed/H1"].get("True", 0), "H1_path_true": t["path/H1"].get("True", 0),
                      "H3_speed_true": t["speed/H3"].get("True", 0), "H3_path_true": t["path/H3"].get("True", 0),
                      "H2_path": t["path/H2"], "H2_speed": t["speed/H2"], "n_seeds": st["n_seeds"]}
    out["H4_same_scale_fraction"] = st.get("H4_same_scale_fraction")
    out["H4_preregistered"] = v.get("H4_same_scale_v3_vs_mixunit")
    return out


def probe_tex(pb):
    n = pb["base"]["n_seeds"]
    L = ["% Generated by tools/make_paper2_extra_tables.py -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering\footnotesize",
         r"\caption{Representation probe: how often each verdict is reached over " + str(n) + " cross-validation "
         r"fold seeds (post hoc stability check of the preregistered analysis, which used one seed). H1: a "
         r"linear readout of the reference quantity from the hidden states beats the permutation null; H3: the "
         r"readout loses its correlation when the four frames are replaced by the first frame; H2: whether the "
         r"readout is better explained by the image-plane or the floor-plane quantity (untestable when the "
         r"control condition does not separate them).}",
         r"\label{tab:probe}", r"\resizebox{\linewidth}{!}{%", r"\begin{tabular}{lcccccc}", r"\toprule",
         r"Model & H1 speed & H1 path & H3 speed & H3 path & H2 path & H2 speed \\", r"\midrule"]
    names = {"base": "unadapted", "native": "CourtDyn-native", "v3": "metre-only v3", "mixunit": "mixed-unit"}
    for m in ("base", "native", "v3", "mixunit"):
        e = pb[m]
        lab = lambda k: "excluded" if k == "None" else k.lower()     # verdict labels printed as plain words
        h2p = ", ".join(f"{lab(k)} {v}" for k, v in sorted(e["H2_path"].items(), key=lambda kv: -kv[1]))
        h2s = ", ".join(f"{lab(k)} {v}" for k, v in sorted(e["H2_speed"].items(), key=lambda kv: -kv[1]))
        L.append(f"{names[m]} & {e['H1_speed_true']}/{n} & {e['H1_path_true']}/{n} & {e['H3_speed_true']}/{n} & "
                 f"{e['H3_path_true']}/{n} & {h2p} & {h2s} \\\\")
    L += [r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
    return "\n".join(L) + "\n"


def build():
    TABLES.mkdir(parents=True, exist_ok=True)
    sb, rg, t36, pb = seeds_block(), rtc_groups(), t36_block(), probe_block()
    (TABLES / "backbone_seeds.tex").write_text(seeds_tex(sb), encoding="utf-8")
    (TABLES / "seed_labels.tex").write_text(seed_labels_tex(sb), encoding="utf-8")
    (TABLES / "rtc_supp.tex").write_text(rtc_tex(rg), encoding="utf-8")
    (TABLES / "t36_supp.tex").write_text(t36_tex(t36), encoding="utf-8")
    (TABLES / "repr_probe_supp.tex").write_text(probe_tex(pb), encoding="utf-8")
    rtc_numbers = [{k: g[k] for k in ("name", "adapter", "H1", "H3", "H4", "H5", "H6_v3", "H6_mix")} for g in rg]
    return {"seeds": sb, "rtc": rtc_numbers, "probe": pb}


if __name__ == "__main__":
    import sys
    print(json.dumps(build()["rtc"], indent=1)[:1500])
    sys.exit(0)
