#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Per-item centimetre/metre answer ratios of the mixed-unit adapters (post hoc, after an external review).

For each seed (42, 43, 44), test clip (Q1_top, Q2_top) and family (speed, path), pairs the
centimetre-arm and metre-arm answers of the same item (explicit prompts, full frames) and reports the
distribution of r_i = cm_i / (100 m_i): median, inter-quartile range, and the share of items within a
factor of two (0.5 <= r_i <= 2) and within a factor of 1.25 (0.8 <= r_i <= 1.25) of exact conversion.  The
preregistered rule uses the median ratio R only; this adds how many items individually convert.

Writes results/courtdyn/m1_mixunit/item_ratios.json and .md.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
EV = ROOT / "results" / "courtdyn" / "m1_mixunit" / "eval"
SEEDS = {"42": "mixunit", "43": "mixunit_s43", "44": "mixunit_s44"}
CLIPS = {"Q1": "Q1_top_0-30", "Q2": "Q2_top_480-510"}
FAMS = {"speed": "dynamics_speed_player", "path": "dynamics_path_player"}


def rows(path):
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def main() -> int:
    out = {"definition": "r_i = cm_i / (100 * m_i) over items with both answers parsed and m_i > 0",
           "cells": {}}
    for seed, pre in SEEDS.items():
        for clip, seq in CLIPS.items():
            d = EV / f"{pre}_{seq}_full"
            cm = {(r["index"], r["category"]): r.get("prediction") for r in rows(d / "cm_height.jsonl")}
            m = {(r["index"], r["category"]): r.get("prediction") for r in rows(d / "m_height.jsonl")}
            for fam, cat in FAMS.items():
                keys = [k for k in cm if k[1] == cat and k in m]
                r = np.array([cm[k] / (100.0 * m[k]) for k in keys
                              if cm[k] is not None and m[k] is not None and m[k] > 0], dtype=float)
                cell = {"n_items": int(len(keys)), "n_paired": int(len(r)),
                        "distinct_cm": int(len({cm[k] for k in keys if cm[k] is not None}))}
                if len(r):
                    q1, med, q3 = np.percentile(r, [25, 50, 75])
                    cell.update({"median": float(med), "iqr": [float(q1), float(q3)],
                                 "share_within_factor2": float(np.mean((r >= 0.5) & (r <= 2.0))),
                                 "share_within_25pct": float(np.mean((r >= 0.8) & (r <= 1.25)))})
                out["cells"][f"s{seed}/{clip}/{fam}"] = cell
    # summaries across the six seed x clip cells per family
    for fam in FAMS:
        cs = [c for k, c in out["cells"].items() if k.endswith(fam) and "median" in c]
        out[f"summary_{fam}"] = {
            "median_range": [min(c["median"] for c in cs), max(c["median"] for c in cs)],
            "share_within_factor2_range": [min(c["share_within_factor2"] for c in cs), max(c["share_within_factor2"] for c in cs)],
            "share_within_25pct_range": [min(c["share_within_25pct"] for c in cs), max(c["share_within_25pct"] for c in cs)],
            "n_cells": len(cs)}
    dst = EV.parent / "item_ratios.json"
    dst.write_text(json.dumps(out, indent=1), encoding="utf-8")
    lines = ["| cell | n | distinct cm | median r | IQR | within x2 | within x1.25 |", "|---|---|---|---|---|---|---|"]
    for k, c in out["cells"].items():
        if "median" in c:
            lines.append(f"| {k} | {c['n_paired']} | {c['distinct_cm']} | {c['median']:.2f} | "
                         f"[{c['iqr'][0]:.2f}, {c['iqr'][1]:.2f}] | {100 * c['share_within_factor2']:.0f}% | "
                         f"{100 * c['share_within_25pct']:.0f}% |")
    dst.with_suffix(".md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    # LaTeX table for the supplement
    T = ["% Generated by tools/mixunit_item_ratios.py -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering\footnotesize", r"\setlength{\tabcolsep}{4pt}",
         r"\caption{Per-item centimetre/metre answer ratios of the mixed-unit adapters, explicit prompts.}",
         r"\label{tab:item_ratios}", r"\begin{tabular}{llcccccc}", r"\toprule",
         r"Seed & clip & family & distinct cm & median $r_i$ & IQR & within $\times2$ & within $\times1.25$ \\", r"\midrule"]
    for k, c in out["cells"].items():
        if "median" not in c:
            continue
        s, clip, fam = k.split("/")
        T.append(f"{s[1:]} & {clip} & {fam} & {c['distinct_cm']} & {c['median']:.2f} & "
                 f"[{c['iqr'][0]:.2f}, {c['iqr'][1]:.2f}] & {100 * c['share_within_factor2']:.0f}\\% & "
                 f"{100 * c['share_within_25pct']:.0f}\\% \\\\")
    T += [r"\bottomrule", r"\end{tabular}",
          r"\par\vspace{3pt}\begin{flushleft}\footnotesize $r_i = \hat y_{\mathrm{cm},i}/(100\,\hat y_{\mathrm{m},i})$ "
          r"over the 140 items of each cell with both answers parsed; exact conversion gives $r_i=1$. "
          r"``within $\times2$'': $0.5\le r_i\le2$; ``within $\times1.25$'': $0.8\le r_i\le1.25$. The preregistered "
          r"rule uses the median ratio $R$ of the same pairs.\end{flushleft}", r"\end{table}"]
    (ROOT / "paper2" / "manuscript_v2" / "tables" / "mixunit_item_ratios.tex").write_text("\n".join(T) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
