#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""LaTeX table of the nested-CV probe re-analysis next to the preregistered verdicts.

Reads results/courtdyn/repr_probe/{verdict.json, nested_reanalysis.json}; writes
paper2/manuscript_v2/tables/repr_probe_nested.tex.  Returns the tex as a string for the audit.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RP = ROOT / "results" / "courtdyn" / "repr_probe"
NAMES = {"base": "unadapted", "native": "CourtDyn-native", "v3": "metre-only v3", "mixunit": "mixed-unit"}


def build() -> str:
    v = json.loads((RP / "verdict.json").read_text(encoding="utf-8"))
    v = v["models"] if "models" in v else v
    n = json.loads((RP / "nested_reanalysis.json").read_text(encoding="utf-8"))["models"]
    L = ["% Generated by tools/repr_probe_nested_table.py -- do not edit by hand.",
         r"\begin{table}[t]", r"\centering\footnotesize", r"\setlength{\tabcolsep}{4pt}",
         r"\caption{Representation probe: preregistered pipeline and the nested re-analysis.}",
         r"\label{tab:probe_nested}", r"\begin{tabular}{llcccccc}", r"\toprule",
         r" & & \multicolumn{3}{c}{preregistered (selection on all items)} & \multicolumn{3}{c}{nested (selection inside folds)} \\",
         r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}",
         r"Model & family & $\rho_{\mathrm{full}}$ & $\rho_{\mathrm{static}}$ & dep. & $\rho_{\mathrm{full}}$ & $\rho_{\mathrm{static}}$ & dep. \\",
         r"\midrule"]
    yn = lambda b: "yes" if b else "no"
    for m in ("base", "native", "v3", "mixunit"):
        for fam in ("speed", "path"):
            p = v[m]["families"][fam]["H3"]
            q = n[m][fam]["H3"]
            L.append(f"{NAMES[m]} & {fam} & {p['rho_full_q2_oof']:.2f} & {p['rho_static4']:.2f} & {yn(p['motion_dependent'])} & "
                     f"{q['rho_full_q2_oof']:.2f} & {q['rho_static4_oof']:.2f} & {yn(q['motion_dependent'])} \\\\")
    L += [r"\bottomrule", r"\end{tabular}",
          r"\par\vspace{3pt}\begin{flushleft}\footnotesize Q2\_top, 140 items per family. $\rho_{\mathrm{full}}$: "
          r"out-of-fold Spearman of the probe against log metre on the four-frame items; $\rho_{\mathrm{static}}$: the "
          r"same probe applied to the first-frame$\times4$ features of the same items; dep.\ = motion-dependent "
          r"($\rho_{\mathrm{static}}\le\rho_{\mathrm{full}}-0.30$). Preregistered: feature chosen on all overhead items, "
          r"static items scored by a probe fit on all items. Nested: feature and penalty chosen inside each outer "
          r"training fold, static items scored by the probe of the fold that holds them out; H1 holds for every row "
          r"against 200 full-pipeline permutations.\end{flushleft}", r"\end{table}"]
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    tex = build()
    (ROOT / "paper2" / "manuscript_v2" / "tables" / "repr_probe_nested.tex").write_text(tex, encoding="utf-8")
    print("written")
    sys.exit(0)
